# Generated by Django 3.2.3 on 2021-05-24 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='rdate',
            new_name='ReleaseDate',
        ),
    ]
